AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  webhook-pattern

  Webhook Pattern

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  Queue:
    Type: AWS::SQS::Queue

  DynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: message_id
          AttributeType: S
      KeySchema:
        - AttributeName: message_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  MainFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.9
      Events:
        DefaultEndpoint:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref Queue
          DYNAMO_TABLE: !Select [ 1, !Split [ '/', !GetAtt DynamoDb.Arn ] ]
          API_ROOT_PATH: /Prod

  ProcessMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.process_message
      Runtime: python3.9
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Select [ 1, !Split [ '/', !GetAtt DynamoDb.Arn ] ]
      Environment:
        Variables:
          QUEUE_URL: !Ref Queue
          DYNAMO_TABLE: !Select [ 1, !Split [ '/', !GetAtt DynamoDb.Arn ] ]
          API_ROOT_PATH: /Prod

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Webhook Pattern function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  MainFunction:
    Description: "Main function ARN"
    Value: !GetAtt MainFunction.Arn
  MainFunctionIamRole:
    Description: "Implicit IAM Role created for Main function"
    Value: !GetAtt MainFunctionRole.Arn
